[package]
name = "input"
version = "0.10.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
license = "MPL-2.0"

[features]

[dependencies]
sdl2.workspace = true
gameplay.workspace = true
serde.workspace = true
