kind: pipeline
  name: default

steps:
- name: test
  image: rust:1.61
  commands:
  - apt update
  - apt install -y libsdl2-dev libsdl2-gfx-dev libsdl2-mixer-dev cmake
  - cargo check --verbose --all
  - cargo test --verbose --all
- name: rustfmt
  image: rust:1.61
  commands:
  - rustup component add rustfmt
  - cargo fmt --all -- --check
