[workspace]
members = ["wad", "game", "gamelib"]

[profile.release]
lto = true
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
debug = true
opt-level = 2

[profile.bench]
debug = false
opt-level = 3