[workspace]
members = ["wad", "game-exe", "gameplay", "render/traits", "render/software", "sound/traits", "sound/sdl2", "multigen"]

[profile.release]
lto = true
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
debug = true
opt-level = 2

[profile.bench]
debug = false
opt-level = 3
