[workspace]
members = ["wad", "game-exe", "gameplay", "gamestate", "gamestate-traits", "intermission/doom", "statusbar/doom", "input", "menu/doom", "render/traits", "render/software", "sound/traits", "sound/sdl2", "multigen", "hud-util", "hud-messages/doom"]

[profile.release]
lto = true
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
debug = true
opt-level = 2

[profile.bench]
debug = false
opt-level = 3
