[workspace]
members = ["wad", "game", "gameplay", "rendering", "r-software"]

[profile.release]
lto = true
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
debug = true
opt-level = 0

[profile.bench]
debug = false
opt-level = 3
