[workspace]
members = [
    "wad",
    "game-exe",
    "gameplay",
    "gamestate",
    "gamestate-traits",
    "intermission/doom",
    "statusbar/doom",
    "input",
    "menu/doom",
    "render/render-target",
    "render/software",
    "sound/traits",
    "sound/sdl2",
    "sound/nosnd",
    "multigen",
    "hud-util",
    "hud-messages/doom",
    "finale/doom",
]

[workspace.package]
version = "0.9.0"

[workspace.dependencies]
wad = { path = "./wad" }
input = { path = "./input" }
menu-doom = { path = "./menu/doom" }
gameplay = { path = "./gameplay" }
gamestate = { path = "./gamestate" }
gamestate-traits = { path = "./gamestate-traits" }
intermission-doom = { path = "./intermission/doom" }
hud-util = { path = "./hud-util" }
hud-doom = { path = "./hud-messages/doom" }
finale-doom = { path = "./finale/doom" }
statusbar-doom = { path = "./statusbar/doom" }

sound-traits = { path = "./sound/traits" }
sound-sdl2 = { path = "./sound/sdl2" }
sound-nosnd = { path = "./sound/nosnd" }
render-target = { path = "./render/render-target" }
render-soft = { path = "./render/software" }
render-opengl = { path = "./render/opengl" }

glam = "*"
golem = { git = "https://github.com/flukejones/golem/" }
#sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", features = ["mixer", "bundled"] }
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", features = ["mixer"] }

gumdrop = "~0.8"

log = "*"
env_logger = { version = "^0.10" }
dirs = "~5.0"
toml = "0.7"
serde = { version = "1.0", features = ["serde_derive"] }

#[workspace.dependencies.cargo-husky]
#version = "1"
#default-features = false
#features = ["user-hooks"]

[profile.release]
lto = "fat"
debug = false
opt-level = "z"
panic = "abort"
strip = "symbols"
codegen-units = 1

[profile.dev]
debug = true
opt-level = 3

[profile.bench]
debug = false
opt-level = 3
codegen-units = 1
