[workspace]
members = ["wad", "game", "gameplay", "render-traits", "render-soft", "sound-traits", "sound-sdl2"]

[profile.release]
lto = true
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
debug = true
opt-level = 0

[profile.bench]
debug = false
opt-level = 3
