[package]
name = "room4doom"
version = "0.11.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
license = "MPL-2.0"
build = "../build.rs"

[[bin]]
name = "room4doom"
path = "src/main.rs"

[dependencies]
gumdrop.workspace = true
input.workspace = true
menu-doom.workspace = true
gameplay.workspace = true
gamestate.workspace = true
gamestate-traits.workspace = true

intermission-doom.workspace = true
hud-doom.workspace = true
finale-doom.workspace = true
statusbar-doom.workspace = true

sound-traits.workspace = true
sound-sdl2.workspace = true
render-traits.workspace = true
render-soft.workspace = true
wad.workspace = true

# utility deps
env_logger.workspace = true
dirs.workspace = true
toml.workspace = true
serde.workspace = true
