[package]
name = "hud-util"
version = "0.2.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"

[dependencies]
wad = { path = "../wad" }
gamestate-traits = { path = "../gamestate-traits" }
# versions are set by game-exe crate
log = "*"
