[package]
name = "sound-nosnd"
version = "0.1.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
build = "../../build.rs"

[features]

[dependencies]
wad.workspace = true
sound-traits.workspace = true
log.workspace = true
glam.workspace = true
serde.workspace = true
