[package]
name = "sound-sdl2"
version = "0.1.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
build = "../../build.rs"

[features]

[dependencies]
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", features = ["mixer"] }
wad = { path = "../../wad" }
sound-traits = { path = "../traits" }
# versions are set by game-exe crate
log = "*"
glam = "*"
# Required for config options
serde = { version = "*", features = ["serde_derive"] }
