[package]
name = "gamestate-traits"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sdl2.workspace = true
gameplay.workspace = true
render-trait.workspace = true
sound-traits.workspace = true
wad.workspace = true
