[package]
name = "gamestate-traits"
version = "0.2.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"

[dependencies]
sdl2.workspace = true
gameplay.workspace = true
render-traits.workspace = true
sound-traits.workspace = true
wad.workspace = true
