[package]
name = "statusbar-doom"
version = "0.1.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"

[dependencies]
wad = { path = "../../wad" }
gamestate-traits = { path = "../../gamestate-traits" }
hud-lines = { path = "../../hud-lines" }
# versions are set by game-exe crate
log = "*"
