[package]
name = "menu-doom"
version = "0.2.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"

[dependencies]
gamestate-traits.workspace = true
sound-traits.workspace = true
wad.workspace = true
log.workspace = true
