[package]
name = "render-soft"
version = "0.9.1"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
build = "../../build.rs"

[dependencies]
glam = "*"
gameplay = { path = "../../gameplay" }
render-traits = { path = "../traits" }

[dev-dependencies]
wad = { path = "../../wad" }
