[package]
name = "intermission-doom"
version = "0.1.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"

[dependencies]
wad = { path = "../../wad" }
game-traits = { path = "../../game-traits" }
# versions are set by game-exe crate
log = "*"
