[package]
name = "intermission-doom"
version = "0.1.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"

[dependencies]
wad.workspace = true
gamestate-traits.workspace = true
gameplay.workspace = true
log.workspace = true
