[package]
name = "gamestate"
version = "0.11.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
gameplay = { path = "../gameplay" }
gamestate-traits = { path = "../gamestate-traits" }
sound-traits = { path = "../sound/traits" }
sound-sdl2 = { path = "../sound/sdl2" }
sound-nosnd = { path = "../sound/nosnd" }
menu-doom = { path = "../menu/doom" }
wad = { path = "../wad" }
# utility deps
toml = "*"
serde = { version = "1.0", features = ["serde_derive"] }
