[package]
name = "gameplay"
version = "0.9.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
build = "../build.rs"

[dependencies]
sound-traits = { path = "../sound-traits" }
sound-sdl2 = { path = "../sound-sdl2" }
wad = { path = "../wad" }
glam = "0.8.5"
log = "^0.4"
