[package]
name = "gameplay"
version = "0.10.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
build = "../build.rs"

[features]
default = []
null_check = []

[dependencies]
sound-traits = { path = "../sound-traits" }
sound-sdl2 = { path = "../sound-sdl2" }
wad = { path = "../wad" }
glam = "~0.20"
log = "^0.4"
