[package]
name = "gameplay"
version = "0.11.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
build = "../build.rs"

[features]
null_check = []

[dependencies]
sound-traits.workspace = true
sound-sdl2.workspace = true
wad.workspace = true
glam.workspace = true
log.workspace = true
