[package]
name = "render-target"
version = "1.0.0"
authors = ["Luke Jones <luke@ljones.dev>"]
edition = "2021"
build = "../../build.rs"

[dependencies]
gameplay.workspace = true
golem.workspace = true
sdl2.workspace = true
serde.workspace = true
