[package]
name = "render-trait"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "../../build.rs"

[dependencies]
gameplay.workspace = true

[dev-dependencies]
wad.workspace = true
